version: '3.6'

services:
  bk:
    build: .

    ports:
      - 80:8080
    volumes:
      - ./:/root/app
    restart: always

  db:
    image: postgres:alpine

    expose:
      - 5432
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/

    environment:
      POSTGRES_DB: suplement-prod-db
      POSTGRES_USER: suplement-prod-app
      POSTGRES_PASSWORD: 7683x807cjyid
    restart: always
